name: h3_od

channels:
  - esri
  - conda-forge

dependencies:
  - arcgis>=2.4.0
  - black>=21
  - jupyterlab
  - jupyterlab_code_formatter
  - nodejs
  - pandoc
  - pip
  - pytest
  - pyarrow
  - pyyaml
  - pip:
    - autodocsumm
    - azure-storage-blob
    - build
    - bump2version
    - furo
    - nbsphinx
    - placekey
    - h3==4.1.*
    - sphinx
    - sphinxcontrib-youtube
    - sphinx-autodoc-typehints
    - sphinx-copybutton
    - twine
