name: h3_od

channels:
  - esri
  - conda-forge

dependencies:
  - arcgis>=2.4.0
  - black>=21
  - jupyterlab
  - jupyterlab_code_formatter
  - nodejs
  - pandoc
  - pip
  - pytest
  - pyyaml
  - pip:
    - azure-storage-blob
    - build
    - bump2version
    - h3==4.*
    - mkdocs
    - mkdocs-glightbox
    - mkdocs-include-markdown-plugin
    - mkdocs-jupyter
    - mkdocs-material
    - mkdocstrings[python]>=0.18
    - placekey
    - twine
